# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project'
require 'bubble-wrap'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'TestHTTP'
  app.codesign_certificate = 'iPhoneDeveloper: Christian Guenter (7KYQMZHJNW)'
end
